version: "3.9"
services:
    db:
        image: mcr.microsoft.com/mssql/server:latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=p2ompiTJ
        ports:
            - 1433:1433
        volumes:
            - ./database/volume-db:/var/opt/mssql/data
