version: "3.9"

services:
  db:
    restart: always
    build:
      ./database
    image: db
    container_name: PSQL
    environment:
      - POSTGRES_DB=url-short
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p2ompiTJ
    ports:
      - "5432:5432"
    volumes:
      - ./database/volume-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: none
  api:
    build: ./
    container_name: API
    command: ["./apiserver"]
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "8080:8080"
