version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mango
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - './volume/mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo 127.0.0.1:27017 --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none
  api:
    build: ./
    depends_on:
      mongo:
        condition: service_healthy
    links:
      - mongo
    container_name: API
    command: [ "./cmd/api" ]
    ports:
      - "8080:8080"